var courses = 
    [
       
    {"id": 1,
    "title": "2020 Complete Python Bootcamp: From Zero to Hero in Python",
    "instructor": "Jose Portilla",
    "price": 199.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/240x135/567828_67d0.jpg"},
    {"id": 2,
    "title": "The Web Developer: Go from Beginner to Expert (2020 Edition)",
    "instructor": "Colt Steel",
    "price": 144.99,
    "level": "Intermediate",
    "img": "https://img-a.udemycdn.com/course/240x135/625204_436a_2.jpg"},
    {"id": 3,
    "title": "Machine Learning A-Z™: Hands-On Python & R In Data Science",
    "instructor": "Kirill Eremenko",
    "price": 89.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/240x135/950390_270f_3.jpg"},
    {"id": 4,
    "title": "iOS 13 & Swift 5 - The Complete iOS App Development",
    "instructor": "Tim Buchalka",
    "price": 134.99,
    "level": "Intermediate",
    "img": "https://img-a.udemycdn.com/course/240x135/1315702_75f4_2.jpg"},
    {"id": 5,
    "title": "Angular - The Complete Guide (2020 Edition)",
    "instructor": "Maximilian Schwarzmuiller",
    "price": 49.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/240x135/756150_c033_2.jpg"},
    {"id": 6,
    "title": "Django Web Development: All You Need learn",
    "instructor": "Jose Portilla",
    "price": 34.99,
    "level": "Intermediate",
    "img": "https://img-a.udemycdn.com/course/240x135/903744_8eb2.jpg"},
    {"id": 7,
    "title": "The Complete JavaScript Course: Build Real Projects!",
    "instructor": "Jonas Schmedtmann",
    "price": 199.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/240x135/851712_fc61_5.jpg"},
    {"id": 8,
    "title": "The Data Science Course: Complete Data Science",
    "instructor": "365 Career",
    "price": 89.99,
    "level": "Intermediate",
    "img": "https://img-a.udemycdn.com/course/240x135/1754098_e0df_3.jpg"},
    {"id": 9,
    "title": "React - The Complete Guide  (2020 Edition)",
    "instructor": "Maximilian Schwarzmuiller",
    "price": 222.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/240x135/1362070_b9a1_2.jpg"},
    {"id": 10,
    "title": "The Ultimate MySQL: Go from SQL Beginner to Expert",
    "instructor": "Colt Steele",
    "price": 34.99,
    "level": "Intermediate",
    "img": "https://img-a.udemycdn.com/course/240x135/1187016_51b3.jpg"},
    {"id": 11,
    "title": "The Complete Node.js Developer Course: Build Real Projects!",
    "instructor": "Andrew Mead",
    "price": 234.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/240x135/1107524_5f3d.jpg"},
    {"id": 12,
    "title": "Deep Learning A-Z™: Hands-On Artificial Neural Networks",
    "instructor": "Kirill Eremenko",
    "price": 99.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/240x135/1151632_de9b.jpg"},
    {"id": 13,
    "title": "JavaScript: Understanding the Weird Parts And Practices",
    "instructor": "Anthony Alicea",
    "price": 199.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/240x135/364426_2991_5.jpg"},
    {"id": 14,
    "title": "Vue JS - The Complete Guide (incl. Vue Router & Vuex)",
    "instructor": "Anthony Steele",
    "price": 129.99,
    "level": "Intermediate",
    "img": "https://img-a.udemycdn.com/course/240x135/995016_ebf4.jpg"},
    {"id": 15,
    "title": "Python and Django Full Stack Web Developer Bootcamp",
    "instructor": "Portilla Career",
    "price": 134.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/240x135/822444_a6db.jpg"},
]

    export default courses;    